apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-lep-two
  labels:
    app: my-app-lep-two
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-lep-two
  template:
    metadata:
      labels:
        app: my-app-lep-two
    spec: 
      imagePullSecrets:
      - name: my-registry-key-two
      containers:
      - name: my-app-lep-two
        image: 767397811804.dkr.ecr.us-east-1.amazonaws.com/my-app-lep:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 3000